[package]
name = "sniffer"
version.workspace = true
edition.workspace = true

[dependencies]
sniffer-cli = { path = "../sniffer-cli" }
package-reader = { path = "../package-reader" }
core = { path = "../core" }

